export const repoBox = [
  {
    id: 1,
    title: "Owambe",
    url: "https://github.com/Chiziterex/Owambe",
    stars: 0,
    Forks: 0,
    language: "HTML",
    Description:
      "If you want to be updated on events going on in your vicinity, you've come to the right place.",
  },
  {
    id: 2,
    title: "GPA-CALCULATOR",
    url: "https://github.com/Chiziterex/GPA-CALCULATOR",
    stars: 0,
    Forks: 0,
    language: "HTML",
    Description: "An easy way to calculate your results at the end of the semester",
  },
  {
    id: 3,
    title: "Improved-Waste-Management",
    url: "https://github.com/Chiziterex/Improved-Waste-Management",
    stars: 0,
    Forks: 0,
    language: "CSS",
    Description: "None",
  },
  {
    id: 4,
    title: "COLOR-MIXER",
    url: "https://github.com/Chiziterex/COLOR-MIXER",
    stars: 0,
    Forks: 0,
    language: "Javascript",
    Description: "A fun way to mix your colours",
  },
  {
    id: 5,
    title: "WIFI-LOGIN-FORM",
    url: "https://github.com/Chiziterex/WIFI-LOGIN-FORM",
    stars: 0,
    Forks: 0,
    language: "CSS",
    Description: "It's a required form needed to filled before having access to a wifi network.",
  },
  {
    id: 6,
    title: "sushi-site",
    url: "https://github.com/Chiziterex/sushi-site",
    stars: 0,
    Forks: 1,
    language: "HTML",
    Description: "None",
  },
  {
    id: 7,
    title: "Electronics-site",
    url: "https://github.com/Chiziterex/Electronics-site",
    stars: 0,
    Forks: 0,
    language: "CSS",
    Description: "None",
  },
  {
    id: 8,
    title: "Love-calculator",
    url: "https://github.com/Chiziterex/Love-calculator-",
    stars: 0,
    Forks: 0,
    language: "CSS",
    Description: "None",
  },
  {
    id: 9,
    title: "Phone",
    url: "https://github.com/Chiziterex/Phone",
    stars: 0,
    Forks: 0,
    language: "CSS",
    Description: "None",
  },
  {
    id: 10,
    title: "iphone-clone",
    url: "https://github.com/Chiziterex/iphone-clone",
    stars: 0,
    Forks: 0,
    language: "HTML",
    Description: "It's an imitation of an iphone home screen",
  },
  {
    id: 11,
    title: "profile",
    url: "https://github.com/Chiziterex/profile",
    stars: 0,
    Forks: 0,
    language: "HTML",
    Description: "A clone of a Github Profile",
  },
  {
    id: 12,
    title: "cloned-portfolio",
    url: "https://github.com/Chiziterex/cloned-portfolio",
    stars: 0,
    Forks: 0,
    language: "CSS",
    Description: "A replica of a portfolio",
  },
  {
    id: 13,
    title: "Grid-layout",
    url: "https://github.com/Chiziterex/Grid-layout",
    stars: 0,
    Forks: 0,
    language: "CSS",
    Description: "None",
  },
  {
    id: 14,
    title: "Simple-login-Form",
    url: "https://github.com/Chiziterex/Simple-login-Form",
    stars: 0,
    Forks: 0,
    language: "CSS",
    Description: "It's a clone of a simple login form",
  },
  {
    id: 15,
    title: "ubay-site",
    url: "https://github.com/Chiziterex/ubay-site",
    stars: 0,
    Forks: 0,
    language: "HTML",
    Description: "a book site",
  },
];
